version: 0.2
env:
  variables:
    STACK: staging
  parameter-store:
    S3_BUCKET: project-yalk-${STACK}-ssm-s3-website-bucket
    CDN_DISTRIBUTION_ID: project-yalk-${STACK}-ssm-cloudfront-id
    NEXT_PUBLIC_HOSTNAME: project-yalk-${STACK}-ssm-s3-website-bucket
    NEXT_PUBLIC_STAGE: ${STACK}
    NEXT_PUBLIC_APPLICATION: project-yalk-${STACK}-ssm-application

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - printenv
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn workspace @yalk/web-client install
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - yarn workspace @yalk/web-client build
  post_build:
    commands:
      - echo web-client build completed on `date`
      - aws s3 cp packages/web-client/out s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
      - aws cloudfront create-invalidation --distribution-id ${CDN_DISTRIBUTION_ID} --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: 'packages/web-client/out*'
  discard-paths: yes